<?php

// Each text string may include parameter substitution - refer to SPRINTF() function

$array['e0001'] = "Start Date cannot be later than End Date";
$array['e0002'] = "End Date cannot be earlier than Start Date";
$array['e0003'] = "This is the lowest level - no children allowed";
$array['e0004'] = "Cannot be empty";
$array['e0005'] = "Value too large (%1\$s)";
$array['e0006'] = "Must be an integer";
$array['e0007'] = "Must be greater than 0";
$array['e0008'] = "Must not be greater than %1\$s";
$array['e0009'] = "Value has already been used";

$array['e0010'] = "";
$array['e0011'] = "";
$array['e0012'] = "";
$array['e0013'] = "";
$array['e0014'] = "";
$array['e0014'] = "";
$array['e0015'] = "";
$array['e0016'] = "";
$array['e0017'] = "";
$array['e0018'] = "";
$array['e0019'] = "";

$array['e0020'] = "";
$array['e0021'] = "";
$array['e0022'] = "";
$array['e0023'] = "";
$array['e0024'] = "";
$array['e0025'] = "";
$array['e0026'] = "";
$array['e0027'] = "";
$array['e0028'] = "";
$array['e0029'] = "";

$array['e0030'] = "";
$array['e0031'] = "";
$array['e0032'] = "";
$array['e0033'] = "";
$array['e0034'] = "";
$array['e0035'] = "";
$array['e0036'] = "";
$array['e0037'] = "";
$array['e0038'] = "";
$array['e0039'] = "";

// the following entries are for MENU and NAVIGATION buttons
$array['Option']           = 'Option';
$array['Person']           = 'Person';
$array['Person Type']      = 'Person Type';
$array['Tree Type']        = 'Tree Type';
$array['Maintain Person']  = 'Maintain Person';
$array['List Person']      = 'List Person';
$array['Maintain Options'] = 'Maintain Options';
$array['List Options']     = 'List Options';
$array['Tree Level']       = 'Tree Level';
$array['Tree Structure']   = 'Tree Structure';
$array['Update Seq No']    = 'Update Seq No';
$array['Nodes']            = 'Nodes';
$array['Parent Nodes']     = 'Parent Nodes';
$array['Child Nodes']      = 'Child Nodes';
$array['Link Children']    = 'Link Children';
$array['Unlink Children']  = 'Unlink Children';

// the following entries are for script TITLES
$array['filepicker.php']            = 'Choose Picture';
$array['option_list.php']           = 'List OPTION';
$array['option_add.php']            = 'Insert OPTION';
$array['option_del.php']            = 'Delete OPTION';
$array['option_enq.php']            = 'Enquire OPTION';
$array['option_popup.php']          = 'Choose OPTION';
$array['option_search.php']         = 'Search OPTION';
$array['option_upd.php']            = 'Update OPTION';
$array['person_list.php']           = 'List PERSON';
$array['person_list(a).php']        = 'List PERSON by PERSON TYPE';
$array['person_add.php']            = 'Insert PERSON';
$array['person_del.php']            = 'Delete PERSON';
$array['person_enq.php']            = 'Enquire PERSON';
$array['person_popup.php']          = 'Choose PERSON';
$array['person_search.php']         = 'Search PERSON';
$array['person_upd.php']            = 'Update PERSON';
$array['pers_opt_xref_list(a).php'] = 'List OPTION by PERSON';
$array['pers_opt_xref_list(b).php'] = 'List PERSON by OPTION';
$array['pers_opt_xref_link(a).php'] = 'Maintain OPTION by PERSON';
$array['pers_opt_xref_link(b).php'] = 'Maintain PERSON by OPTION';
$array['pers_type_list.php']        = 'List PERSON TYPE';
$array['pers_type_add.php']         = 'Insert PERSON TYPE';
$array['pers_type_del.php']         = 'Delete PERSON TYPE';
$array['pers_type_enq.php']         = 'Enquire PERSON TYPE';
$array['pers_type_search.php']      = 'Search PERSON TYPE';
$array['pers_type_upd.php']         = 'Update PERSON TYPE';
$array['tree_type_list.php']        = 'List TREE TYPE';
$array['tree_type_add.php']         = 'Insert TREE_TYPE';
$array['tree_type_del.php']         = 'Delete TREE_TYPE';
$array['tree_type_enq.php']         = 'Enquire TREE_TYPE';
$array['tree_type_search.php']      = 'Search TREE_TYPE';
$array['tree_type_upd.php']         = 'Update TREE_TYPE';
$array['tree_level_list.php']       = 'List TREE LEVEL';
$array['tree_level_add.php']        = 'Insert TREE LEVEL';
$array['tree_level_del.php']        = 'Delete TREE LEVEL';
$array['tree_level_enq.php']        = 'Enquire TREE LEVEL';
$array['tree_level_multi.php']      = 'Update TREE LEVEL SEQ';
$array['tree_level_search.php']     = 'Search TREE LEVEL';
$array['tree_level_upd.php']        = 'Update TREE LEVEL';
$array['tree_node_list.php']        = 'List TREE NODE';
$array['tree_node_add.php']         = 'Insert TREE NODE';
$array['tree_node_del.php']         = 'Delete TREE NODE';
$array['tree_node_enq.php']         = 'Enquire TREE NODE';
$array['tree_node_search.php']      = 'Search TREE_NODE';
$array['tree_node_upd']             = 'Update TREE NODE';
$array['tree_node_snr_list.php']    = 'List NODE Parentage';
$array['tree_node_jnr_list.php']    = 'List NODE Children';
$array['tree_node_jnr_add.php']     = 'Link Children';
$array['tree_node_jnr_popup.php']   = 'Choose Orphan NODE';
$array['tree_structure_list.php']   = 'List TREE Structure';
$array['tree_structure_popup.php']  = 'Choose from TREE Structure';

// the following entries are for field LABELS
$array['E-mail']            = 'E-mail';
$array['External Code']     = 'External Code';
$array['File Name']         = 'File Name';
$array['First Name']        = 'First Name';
$array['Image']             = 'Image';
$array['Initials']          = 'Initials';
$array['Last Name']         = 'Last Name';
$array['Level Description'] = 'Level Description';
$array['Level']             = 'Level';
$array['Nat. Ins. No.']     = 'Nat. Ins. No.';
$array['Node Description']  = 'Node Description';
$array['Node Id']           = 'Node Id';
$array['Node']              = 'Node';
$array['Option']            = 'Option';
$array['Organisation']      = 'Organisation';
$array['Parent Node']       = 'Parent Node';
$array['Parent']            = 'Parent';
$array['Person Type']       = 'Person Type';
$array['Person']            = 'Person';
$array['Picture']           = 'Picture';
$array['Seq']               = 'Seq';
$array['Star Sign']         = 'Star Sign';
$array['Tree Level Id']     = 'Tree Level Id';
$array['Tree Level Seq']    = 'Tree Level Seq';
$array['Tree Level']        = 'Tree Level';
$array['Tree Type']         = 'Tree Type';
$array['Value 1']           = 'Value 1';
$array['Value 2']           = 'Value 2';

return $array;

?>